apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        name: echo-server
        app: echo-server
    spec:
      securityContext:
        runAsUser: 1000
      restartPolicy: Always
      # imagePullSecrets:
      # - name: gcr-json-key
      containers:
      - image: echo-server
        # imagePullPolicy: Always
        name: echo-server
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "100m"
            memory: "100M"
        ports:
        - containerPort: 1323
          name: http

